global:
  scrape_interval: 5s
  evaluation_interval: 5s
 
scrape_configs:
 - job_name : 'Store-app'
   metrics_path: 'Store/actuator/prometheus
   scrape_interval: 5s
   static_configs:
     - targets:['host.docker.internal:8014']
 - job_name : 'Database-app'
   metrics_path: 'Database/actuator/prometheus
   scrape_interval: 5s
   static_configs:
     - targets:['host.docker.internal:8015']
     

