spring.profiles.include: 'acl'

server:
  port: ${PORT:8014}
  servlet:
   context-path: /store

spring:
  cache:
    jcache:
      config: 'classpath:ehcache.xml'
  application:
    name: prova-store-service
  liquibase:
    enabled: false
  security:
    oauth2:      
      resourceserver:
        jwt:
          issuer-uri: ${KK_URL:http://localhost}:${KK_PORT:8282}/auth/realms/prova
          jwk-set-uri: ${KK_URL:http://localhost}:${KK_PORT:8282}/auth/realms/prova/protocol/openid-connect/certs

#  data:
#    rest:
#      basePath: /store
  jpa:
     hibernate:
       show-sql: true
       ddl-auto: none
       naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
     database-platform: org.hibernate.dialect.H2Dialect
#Usare questo dialect x MYSQL     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
     driverClassName: org.h2.Driver
     url: jdbc:h2:mem:store;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
     username: store
     password:

  h2:
   console:
    enabled: true
    settings:
      web-allow-others: true
    path: /h2-console
  devtools:
    livereload:
      port: 35830

#logging:
#  level:
#    root: INFO
#    org.hibernate.SQL: TRACE
#    org.springframework: DEBUG
LOGS_DIR: /temp

gateway:
  baseuri: http://localhost:8080
#8090

jasperreports:
  dir: reports
  debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  show-actuator: true  
